apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-downtime-deploy-demo.fullname" . }}
  labels:
    {{- include "zero-downtime-deploy-demo.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    {{- include "zero-downtime-deploy-demo.selectorLabels" . | nindent 4 }}
